name: Extract Garmin Data

on:
  schedule:
    - cron: '0 11 * * *'  # Run at 8am -3GMT (11am UTC)
  workflow_dispatch:  # Allow manual trigger
    inputs:
      days:
        description: 'Number of days of data to extract'
        required: true
        default: '7'
        type: string

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  USER_ID: ${{ secrets.USER_ID }}
  GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Extract data
      run: npm start
      
    - name: Upload data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: garmin-data
        path: data/
        retention-days: 7  # Keep data for 7 days 