name: Initial Garmin Data Extract

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days of historical data to extract'
        required: true
        default: '30'
        type: string

env:
  NODE_VERSION: '18'
  GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  USER_ID: ${{ secrets.USER_ID }}

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm ci
        npm install -g typescript ts-node @types/node
      
    - name: Create env file
      run: |
        echo "Creating .env file..."
        cat << EOF > .env
        GARMIN_USERNAME=${{ secrets.GARMIN_USERNAME }}
        GARMIN_PASSWORD=${{ secrets.GARMIN_PASSWORD }}
        SUPABASE_URL=${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
        USER_ID=${{ secrets.USER_ID }}
        EOF
      
    - name: Extract historical data
      run: |
        echo "Extracting ${{ github.event.inputs.days }} days of historical data..."
        NODE_OPTIONS="--loader ts-node/esm --no-warnings" ts-node --require dotenv/config --esm src/extractor/GarminExtractor.ts ${{ github.event.inputs.days }}
      
    - name: Upload extracted data
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: garmin-data
        path: data/
        retention-days: 5 